import { NextRequest, NextResponse } from 'next/server';
import { createRouteHandlerClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';
import { refreshAccessToken, getPlaylist } from '@/lib/spotify/client';

/**
 * DEPRECATED: This API route is no longer in use. 
 * We now use Spotify's automatically generated cover images instead of allowing custom uploads.
 * This file is kept for reference but should not be used.
 */
export async function PUT(
  request: NextRequest,
  context: any
) {
  // Return a 410 Gone status to indicate this endpoint is no longer available
  return NextResponse.json({
    error: 'This endpoint is deprecated. Playlist covers are now automatically generated by Spotify.'
  }, { status: 410 });
} 